### ISSUE TITLE
equation about transforming the viewpoint representation into a rotation matrix

### ISSUE THREAD

**Issue by LittleYuer** [xingyizhou/StarMap#10]
Hi Xingyi,

Thanks for contribution.

May I ask why it is e−π/2 / -a rather than e/a in this equation to transform the viewpoint representation into a rotation matrix?
R=RZ(θ)RX(e−π/2)RZ(−a) 

Thanks~

Yuer

**Comment by xingyizhou** [comment]
Hi Yuer,
  Thanks for your interests in our work. This is from Shubham's code https://github.com/shubhtuls/ViewpointsAndKeypoints/blob/1d57050601f4a3f7842b2953be524f47d4f53b36/encoding/encodePose.m#L36. It should reflect the dataset definition.

**Comment by LittleYuer** [comment]
Hi Xingyi,

Thanks for explanation.

Yuer
