### ISSUE TITLE
ImportError: No module named paths

### ISSUE THREAD

**Issue by pra-dan** [xingyizhou/StarMap#14]
I am running the test for the pre-trained model on a colab-notebook: [Here](https://colab.research.google.com/drive/16DrNsHZhddzU2CP8IwZrAhgimIJUSqUl#scrollTo=ZFaGiVsGrjKK) 

I get the error:
```console
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from opts import opts
  File "/content/star/tools/../lib/opts.py", line 4, in <module>
    import ref
  File "/content/star/tools/../lib/ref.py", line 1, in <module>
    import paths 
ImportError: No module named paths
```

Is there an alternative to test it ? @moshanATucsd how did you run it ?

**Comment by moshanATucsd** [comment]
> I am running the test for the pre-trained model on a colab-notebook: [Here](https://colab.research.google.com/drive/16DrNsHZhddzU2CP8IwZrAhgimIJUSqUl#scrollTo=ZFaGiVsGrjKK)
> 
> I get the error:
> 
> ```
> Traceback (most recent call last):
>   File "demo.py", line 8, in <module>
>     from opts import opts
>   File "/content/star/tools/../lib/opts.py", line 4, in <module>
>     import ref
>   File "/content/star/tools/../lib/ref.py", line 1, in <module>
>     import paths 
> ImportError: No module named paths
> ```
> 
> Is there an alternative to test it ? @moshanATucsd how did you run it ?

I cannot access the colab you shared, but mostly likely it's a path error. You can try our repos https://github.com/xingyizhou/StarMap/pull/12, https://github.com/xingyizhou/StarMap/pull/1

**Comment by pra-dan** [comment]
I have made it shareable [HERE](https://colab.research.google.com/drive/16DrNsHZhddzU2CP8IwZrAhgimIJUSqUl?usp=sharing)

**Comment by moshanATucsd** [comment]
> I have made it shareable [HERE](https://colab.research.google.com/drive/16DrNsHZhddzU2CP8IwZrAhgimIJUSqUl?usp=sharing)

AFAIK we need to set some path right before running the demo, you can try my version https://github.com/moshanATucsd/StarMap

**Comment by pra-dan** [comment]
Does it run on Python3 ?

**Comment by moshanATucsd** [comment]
> Does it run on Python3 ?

Which one? The original repo is for python 2, mine is for python 3.

**Comment by pra-dan** [comment]
I am still facing some error after using Python3. I used your repo code. Please have a look : https://colab.research.google.com/drive/16DrNsHZhddzU2CP8IwZrAhgimIJUSqUl?usp=sharing

**Comment by moshanATucsd** [comment]
> I am still facing some error after using Python3. I used your repo code. Please have a look : https://colab.research.google.com/drive/16DrNsHZhddzU2CP8IwZrAhgimIJUSqUl?usp=sharing

I suggest make it work on local Ubuntu first, instead of colab, which can have path issues. You can also checkout https://github.com/moshanATucsd/starmap_semantic_keypoints_with_covariance which has very specific path definitions.

**Comment by pra-dan** [comment]
I did so. I get the same error:
```console
$ python demo.py -demo '290_inp.png' -loadModel 'models/Pascal3D-cpu.pth'
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.upsampling.Upsample' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "demo.py", line 72, in <module>
    main()
  File "demo.py", line 26, in main
    output = model(input_var)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pra-dan/github/starmap/src/models/hg.py", line 105, in forward
    hg = self.hourglass[i](x)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pra-dan/github/starmap/src/models/hg.py", line 45, in forward
    low2 = self.low2(low1)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pra-dan/github/starmap/src/models/hg.py", line 45, in forward
    low2 = self.low2(low1)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pra-dan/github/starmap/src/models/hg.py", line 45, in forward
    low2 = self.low2(low1)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pra-dan/github/starmap/src/models/hg.py", line 54, in forward
    up2 = self.up2(low3)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/upsampling.py", line 141, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "/home/pra-dan/.pyenv/versions/atag/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Upsample' object has no attribute 'align_corners'
```

What could be the reason ?

**Comment by pra-dan** [comment]
Can you share the pytorch and other dependeny you used ?

**Comment by moshanATucsd** [comment]
> Can you share the pytorch and other dependeny you used ?

[requirements.txt](https://github.com/xingyizhou/StarMap/files/5276666/requirements.txt)

**Comment by pra-dan** [comment]
This seems too many dependencies. You are using Conda ?

**Comment by moshanATucsd** [comment]
> This seems too many dependencies. You are using Conda ?

I am using conda. You don't have to install all the dependencies, the most important one is pytorch.

**Comment by pra-dan** [comment]
I see that you ran it on OSX. Also, the pytorch version you are using, is not available for my linux (ubuntu).

**Comment by moshanATucsd** [comment]
> I see that you ran it on OSX. Also, the pytorch version you are using, is not available for my linux (ubuntu).

I have ran in on OSX, ubuntu 16.04 and 18.04

**Comment by samagra14** [comment]
@pra-dan , Were you able to run @moshanATucsd's code? For me it gives the following error:

````
AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats'
````

**Comment by pra-dan** [comment]
@samagra14  I faced the same/similar issue. Actually, the authors have used conda to run their setup along with Python2.7 (maybe)... so I tried to replicate this. But could not do it.

**Comment by samagra14** [comment]
@pra-dan I was able to run everything. Just use pytorch 0.3. and run the following command before running the demo.

````
mv STARMAP_ROOT/lib/paths.py.examples STARMAP_ROOT/lib/paths.py
````

**Comment by pra-dan** [comment]
Thanks Sammy, (I looked into your profile 😉 ). 
Also used conda or without it ?
Would appreciate connecting with you on LinkedIn maybe ... ?

**Comment by pra-dan** [comment]
@samagra14 I can't find any `/STARMAP_ROOT/lib/...`. My tree structure is:
```console
.
├── Framework.jpg
├── images
│   ├── 1227_inp.png
│   ├── 1348_inp.png
│   ├── 1571_inp.png
│   ├── 1916_inp.png
│   ├── 2043_inp.png
│   ├── 290_inp.png
│   ├── 816_inp.png
│   ├── 93_inp.png
│   └── 944_inp.png
├── LICENSE
├── models
│   ├── ObjectNet3D-all-cpu.pth
│   └── Pascal3D-cpu.pth
├── README.md
├── req.txt
└── src
    ├── 290_inp.png
    ├── demo.py
    ├── models
    │   ├── hg.py
    │   ├── __init__.py
    │   ├── layers
    │   │   ├── __init__.py
    │   │   ├── __pycache__
    │   │   │   ├── __init__.cpython-37.pyc
    │   │   │   └── Residual.cpython-37.pyc
    │   │   └── Residual.py
    │   ├── ObjectNet3D-all-cpu.pth
    │   ├── Pascal3D-cpu.pth
    │   └── __pycache__
    │       ├── hg.cpython-37.pyc
    │       └── __init__.cpython-37.pyc
    ├── opts.py
    ├── __pycache__
    │   ├── opts.cpython-37.pyc
    │   └── ref.cpython-37.pyc
    ├── ref.py
    └── utils
        ├── debugger.py
        ├── hmParser.py
        ├── horn87.py
        ├── img.py
        ├── __init__.py
        └── __pycache__
            ├── debugger.cpython-37.pyc
            ├── hmParser.cpython-37.pyc
```

**Comment by samagra14** [comment]
@pra-dan Clone again. you have missed the lib directory present at the root of the project.
https://github.com/xingyizhou/StarMap/tree/master/lib

**Comment by pra-dan** [comment]
Ohk Thanks @samagra14 .

I am going to try it soon. I am going to use mainly
conda with Python2.7
torch==0.3

Please correct me 🛩️

**Comment by pra-dan** [comment]
Ok. I got it working 👍🏽 

Used
- conda with Python2.7
- pytorch 0.3 ( Had to install it via wheel from [here](https://download.pytorch.org/whl/cpu/torch_stable.html) ). The `torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl` worked for me and the `torch-0.3.0.post4-cp27-cp27m-linux_x86_64.whl` didn't
- Followed remaining steps from the repo's README. (model downloading etc)
- followed @samagra14 's advice and copied the paths file

**Comment by samagra14** [comment]
@pra-dan Glad that you were able to run the repo. If possible just submit a PR to correct the readme. At least the PyTorch version should be correctly mentioned. It took me a couple of days to try out all possible versions.

**Comment by pra-dan** [comment]
Sure!

All the versions ! Damn!

**Comment by tute123456** [comment]
holis, en mi caso me sirvio borrar carpetas de instalaciones anteriores de python, ubicadas en la ruta **C:\Users\xxx\AppData\Local\Programs\Python**
