### ISSUE TITLE
SourceChangeWarning

### ISSUE THREAD

**Issue by moshanATucsd** [xingyizhou/StarMap#2]
Hi,

Thanks for the great work! I have tried the code using Python 3.6.1 and Pytorch 0.3.1 on MacOS. However I encountered the following warning

```
python3.6/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
```

I am wondering anyone has seen this before and how to resolve it?

**Comment by xingyizhou** [comment]
Hi Mo,
  This is caused by the different PyTorch version between the trained model and your running environment. The model should work well across different versions. You can follow the training instructions to train the model in your own version if you really want to resolve the warning.

**Comment by moshanATucsd** [comment]
I see, thanks for the advice!
