### ISSUE TITLE
pascalEdgeInfo

### ISSUE THREAD

**Issue by moshanATucsd** [xingyizhou/StarMap#6]
Hi, where is pascalEdgeInfo?

**Comment by xingyizhou** [comment]
It is not used in this project.

**Comment by moshanATucsd** [comment]
I see, I am trying to run visEmbeddingPascal.py, so I am wondering whether pascalEdgeInfo could be provided?

**Comment by xingyizhou** [comment]
Sure, it is here.

pascalEdgeInfo = {
'aeroplane':
   [['left_elevator', 'rudder_lower'], 
    ['right_elevator', 'rudder_lower'], 
    ['rudder_upper', 'rudder_lower'], 
    ['rudder_upper', 'tail'], 
    ['rudder_lower', 'noselanding'], 
    ['left_wing', 'right_wing']],
'bicycle':
   [['head_center', 'left_handle'],
    ['head_center', 'right_handle'],
    ['head_center', 'left_front_wheel'],
    ['head_center', 'right_front_wheel'],
    ['left_front_wheel', 'right_front_wheel'],
    ['seat_back', 'seat_front'],
    ['seat_back', 'left_back_wheel'],
    ['seat_back', 'right_back_wheel'],
    ['left_back_wheel', 'left_pedal_center'], 
    ['right_back_wheel', 'right_pedal_center']],
'boat':
   [['head', 'head_down'],
    ['head', 'head_left'], 
    ['head', 'head_right'], 
    ['head_left', 'tail_left'],
    ['head_right', 'tail_right'], 
    ['tail_right', 'tail_left']],
'bottle':
   [['mouth', 'body_left'],
    ['mouth', 'body_right'],
    ['body_left', 'bottom_left'],
    ['bottom_left', 'bottom'],
    ['bottom', 'bottom_right'],
    ['bottom_right', 'body_right']],
'bus':
   [['body_back_left_upper', 'body_back_right_upper'],
    ['body_back_right_upper', 'body_front_right_upper'], 
    ['body_front_right_upper', 'body_front_left_upper'], 
    ['body_front_left_upper', 'body_back_left_upper'], 
    ['body_back_left_lower', 'body_back_right_lower'],
    ['body_back_right_lower', 'body_front_right_lower'], 
    ['body_front_right_lower', 'body_front_left_lower'], 
    ['body_front_left_lower', 'body_back_left_lower'],
    ['body_back_left_upper', 'body_back_left_lower'],
    ['body_back_right_upper', 'body_back_right_lower'], 
    ['body_front_right_upper', 'body_front_right_lower'], 
    ['body_front_left_upper', 'body_front_left_lower']],
'car':
   [['upper_left_windshield', 'upper_right_windshield'],
    ['upper_right_windshield', 'upper_left_rearwindow'],
    ['upper_left_rearwindow', 'upper_right_rearwindow'],
    ['upper_right_rearwindow', 'upper_left_windshield'],
    ['left_front_light', 'right_front_light'],
    ['right_front_light', 'left_back_trunk'],
    ['right_back_trunk', 'left_back_trunk'],
    ['right_back_trunk', 'left_front_light'],
    ['upper_left_windshield', 'left_front_light'],
    ['upper_right_windshield', 'right_front_light'],
    ['upper_right_rearwindow', 'right_back_trunk'],
    ['upper_left_rearwindow', 'left_back_trunk'],
    ['left_front_wheel', 'left_back_wheel'],
    ['right_front_wheel', 'right_back_wheel'],
    ['left_back_wheel', 'right_back_wheel'],
    ['left_front_wheel', 'right_front_wheel'],],
'chair':
   [['leg_upper_left', 'seat_upper_left'], 
    ['leg_upper_right', 'seat_upper_right'],
    ['leg_lower_left', 'seat_lower_left'],
    ['leg_lower_right', 'seat_lower_right'],
    ['seat_upper_left', 'seat_upper_right'], 
    ['seat_upper_right', 'seat_lower_right'],
    ['seat_lower_right', 'seat_lower_left'],
    ['seat_lower_left', 'seat_upper_left'],
    ['seat_upper_left', 'back_upper_left'],
    ['seat_upper_right', 'back_upper_right'],
    ['back_upper_left', 'back_upper_right']],
'diningtable':
   [['top_upper_left', 'top_upper_right'],
    ['top_upper_right', 'top_lower_right'],
    ['top_lower_right', 'top_lower_left'],
    ['top_lower_left', 'top_upper_left'],
    ['top_upper_left', 'leg_upper_left'],
    ['top_upper_right', 'leg_upper_right'],
    ['top_lower_right', 'leg_lower_right'],
    ['top_lower_left', 'leg_lower_left'],
    
    ['top_up', 'top_left'],
    ['top_left', 'top_down'],
    ['top_down', 'top_right'],
    ['top_right', 'top_up']],
'motorbike':
   [['head_center', 'left_handle_center'],
    ['head_center', 'right_handle_center'],
    ['head_center', 'headlight_center'],
    ['head_center', 'left_front_wheel'],
    ['head_center', 'right_front_wheel'],
    ['head_center', 'front_seat'],
    ['front_seat', 'back_seat'],
    ['back_seat', 'left_back_wheel'],
    ['back_seat', 'left_back_wheel']],
'sofa':
   [['front_bottom_left', 'front_bottom_right'], 
    ['front_bottom_right', 'right_bottom_back'], 
    ['right_bottom_back', 'left_bottom_back'], 
    ['left_bottom_back', 'front_bottom_left'], 
    ['seat_bottom_left', 'seat_bottom_right'], 
    ['seat_bottom_right', 'seat_top_right'], 
    ['seat_top_right', 'seat_top_left'], 
    ['seat_top_left', 'seat_bottom_left'], 
    ['front_bottom_left', 'seat_bottom_left'], 
    ['front_bottom_right', 'seat_bottom_right'], 
    ['right_bottom_back', 'seat_top_right'], 
    ['left_bottom_back', 'seat_top_left'],   
    ['seat_top_left', 'top_left_corner'],   
    ['seat_top_right', 'top_right_corner'], 
    ['top_left_corner', 'top_right_corner']],
'train':
   [['head_left_bottom', 'head_right_bottom'], 
    ['head_right_bottom', 'head_right_top'], 
    ['head_right_top', 'head_left_top'], 
    ['head_left_top', 'head_left_bottom'], 
    ['head_left_bottom', 'mid1_left_bottom'], 
    ['head_right_bottom', 'mid1_right_bottom'], 
    ['head_right_top', 'mid1_right_top'], 
    ['head_left_top', 'mid1_left_top'], 
    ['mid1_left_bottom', 'mid2_left_bottom'], 
    ['mid1_right_bottom', 'mid2_right_bottom'], 
    ['mid1_right_top', 'mid2_right_top'], 
    ['mid1_left_top', 'mid2_left_top'], 
    ['mid2_left_bottom', 'tail_left_bottom'], 
    ['mid2_right_bottom', 'tail_right_bottom'], 
    ['mid2_right_top', 'tail_right_top'], 
    ['mid2_left_top', 'tail_left_top']],
'tvmonitor':
   [['front_bottom_left', 'front_bottom_right'],
    ['front_top_left', 'front_top_right'], 
    ['back_bottom_left', 'back_bottom_right'],
    ['back_top_left', 'back_top_right'], 
    ['front_bottom_left', 'front_top_left'], 
    ['front_bottom_right', 'front_top_right'],
    ['back_bottom_left', 'back_top_left'], 
    ['back_bottom_right', 'back_top_right'],
    ['front_bottom_left', 'back_bottom_left'],
    ['front_bottom_right', 'back_bottom_right'],
    ['front_top_left', 'back_top_left'], 
    ['front_top_right', 'back_top_right'],]
}

**Comment by moshanATucsd** [comment]
Thanks!
