### ISSUE TITLE
Viewpoint estimation

### ISSUE THREAD

**Issue by moshanATucsd** [xingyizhou/StarMap#7]
Hi, 

I am wondering if I want to use StarMap to detect the viewpoint of objects in an image, could I detect the objects first, say I now have the bounding boxes, and then apply StarMap on each bounding box? Will the viewpoint returned by StarMap the same as the viewpoint observed in the original image that contains multiple objects? I am not sure about this because there is a cropping and padding process, because StarMap requires 256x256 input size. 

If the viewpoint is not the same, is there a way to recover the original viewpoint from StarMap output?

**Comment by xingyizhou** [comment]
Hi, 
  Sorry for the late reply. The viewpoint should be the same. Actually we used cropped images from Pascal3D+ to train the network.
