### ISSUE TITLE
A question about the application of this method in human pose estimation

### ISSUE THREAD

**Issue by zhengyuezhi** [xingyizhou/StarMap#8]
If you want to apply the method proposed in the paper in human pose estimation, how to set the data set (mpii)，thank you

**Comment by xingyizhou** [comment]
Hi, 
  Thanks for your interest in our work! If you mean applying the depth map, we have provided our implementation in https://github.com/xingyizhou/pytorch-pose-hg-3d . If you are interested in the single channel heatmap and CanViewFeature, you will need to calculate the mean 2D position of MPII dataset and follow https://github.com/xingyizhou/StarMap/blob/master/lib/datasets/Pascal3D.py#L88 to create the ground truth regression target.

**Comment by YoungXIAO13** [comment]
Hi,

I have a question about the decomposition of the rotation matrix into three Euler angles. Could you tell me how did you get this equation and what is the coordinate ? Thanks

**Comment by xingyizhou** [comment]
Hi, 
  I haven't decomposed the matrix into tree Euler angles. The evaluation is directly done in matrix. In the resnet angle classification baseline, we compose the three angles into matrix, you can find the details at https://github.com/xingyizhou/StarMap/blob/master/tools/EvalCls.py#L20.

**Comment by YoungXIAO13** [comment]
Right, I meant where comes from this equation:
np.dot(RotMat('Z', theta), np.dot(RotMat('X', - (PI / 2 - elevation)), RotMat('Z', - azimuth)))
Is this rotation matrix equals to the one in the projection matrix ?

**Comment by xingyizhou** [comment]
Hi, 
  The equation is from the Viewpoints and Keypoints code https://github.com/shubhtuls/ViewpointsAndKeypoints/blob/1d57050601f4a3f7842b2953be524f47d4f53b36/encoding/encodePose.m#L18 .

**Comment by YoungXIAO13** [comment]
ok, I see. Thanks for your reply.
