### ISSUE TITLE
Evaluation image number

### ISSUE THREAD

**Issue by YoungXIAO13** [xingyizhou/StarMap#9]
Hi,

I noticed that you have tested the viewpoint estimation on the non-occluded and non-truncated subset of the validation set in Pascal3D+. However, I got 2136 images for all the 12 categories while you evaluated on 2113 images in the paper. 
So I'm wondering why you got 23 images less than mine.

**Comment by xingyizhou** [comment]
Hi,
  Our script for converting the raw data is here https://github.com/xingyizhou/StarMap/blob/master/tools/getPascal3DDataset.py. I remembered I have met similar issues but finally I got consistent with keypointsAndViewpoint, you can check this line https://github.com/xingyizhou/StarMap/blob/master/tools/getPascal3DDataset.py#L112 . Actually I didn't remembered exactly if I include or not include the missing images. But the code should fully reflect our evaluation protocol.

**Comment by YoungXIAO13** [comment]
Thx, I'll look into that.
